BEGIN;

CREATE TABLE IF NOT EXISTS public.driver_applications (
    application_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id integer NOT NULL,
    previous_application_id integer,
    attempt_number integer NOT NULL,

    status character varying(20)
        DEFAULT 'PENDING_REVIEW'
        NOT NULL,

    full_name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    email character varying(100) NOT NULL,
    cnic_number character varying(13) NOT NULL,

    license_number character varying(50) NOT NULL,

    vehicle_make character varying(50) NOT NULL,
    vehicle_model character varying(50) NOT NULL,
    vehicle_year integer NOT NULL,
    vehicle_color character varying(30) NOT NULL,
    vehicle_plate_number character varying(20) NOT NULL,
    vehicle_capacity integer DEFAULT 4 NOT NULL,

    submitted_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP
        NOT NULL,

    reviewed_at timestamp without time zone,
    reviewed_by integer,
    review_summary character varying(1000),

    approved_driver_id integer,

    created_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP
        NOT NULL,

    updated_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP
        NOT NULL,

    CONSTRAINT driver_applications_user_attempt_unique
        UNIQUE (user_id, attempt_number),

    CONSTRAINT driver_applications_approved_driver_unique
        UNIQUE (approved_driver_id),

    CONSTRAINT driver_applications_status_check
        CHECK (
            status IN (
                'PENDING_REVIEW',
                'APPROVED',
                'DECLINED'
            )
        ),

    CONSTRAINT driver_applications_attempt_number_check
        CHECK (attempt_number > 0),

    CONSTRAINT driver_applications_cnic_check
        CHECK (cnic_number ~ '^[0-9]{13}$'),

    CONSTRAINT driver_applications_vehicle_year_check
        CHECK (vehicle_year >= 2000),

    CONSTRAINT driver_applications_vehicle_capacity_check
        CHECK (vehicle_capacity > 0),

    CONSTRAINT driver_applications_user_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT driver_applications_previous_fkey
        FOREIGN KEY (previous_application_id)
        REFERENCES public.driver_applications(application_id)
        ON DELETE RESTRICT,

    CONSTRAINT driver_applications_reviewed_by_fkey
        FOREIGN KEY (reviewed_by)
        REFERENCES public.users(user_id)
        ON DELETE SET NULL,

    CONSTRAINT driver_applications_approved_driver_fkey
        FOREIGN KEY (approved_driver_id)
        REFERENCES public.drivers(driver_id)
        ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS public.driver_application_corrections (
    correction_id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    application_id integer NOT NULL,

    field_name character varying(50) NOT NULL,
    instruction character varying(1000) NOT NULL,

    created_by integer NOT NULL,

    created_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP
        NOT NULL,

    CONSTRAINT driver_application_correction_field_unique
        UNIQUE (application_id, field_name),

    CONSTRAINT driver_application_correction_field_check
        CHECK (
            field_name IN (
                'full_name',
                'phone_number',
                'email',
                'cnic_number',
                'license_number',
                'vehicle_make',
                'vehicle_model',
                'vehicle_year',
                'vehicle_color',
                'vehicle_plate_number',
                'vehicle_capacity'
            )
        ),

    CONSTRAINT driver_application_correction_application_fkey
        FOREIGN KEY (application_id)
        REFERENCES public.driver_applications(application_id)
        ON DELETE RESTRICT,

    CONSTRAINT driver_application_correction_admin_fkey
        FOREIGN KEY (created_by)
        REFERENCES public.users(user_id)
        ON DELETE RESTRICT
);


CREATE UNIQUE INDEX IF NOT EXISTS
    uq_driver_applications_pending_user
ON public.driver_applications (user_id)
WHERE status = 'PENDING_REVIEW';


CREATE UNIQUE INDEX IF NOT EXISTS
    uq_driver_applications_active_cnic
ON public.driver_applications (cnic_number)
WHERE status IN ('PENDING_REVIEW', 'APPROVED');


CREATE UNIQUE INDEX IF NOT EXISTS
    uq_driver_applications_active_license
ON public.driver_applications (LOWER(license_number))
WHERE status IN ('PENDING_REVIEW', 'APPROVED');


CREATE UNIQUE INDEX IF NOT EXISTS
    uq_driver_applications_active_plate
ON public.driver_applications (LOWER(vehicle_plate_number))
WHERE status IN ('PENDING_REVIEW', 'APPROVED');


CREATE INDEX IF NOT EXISTS
    idx_driver_applications_user
ON public.driver_applications (user_id);


CREATE INDEX IF NOT EXISTS
    idx_driver_applications_status
ON public.driver_applications (status);


CREATE INDEX IF NOT EXISTS
    idx_driver_application_corrections_application
ON public.driver_application_corrections (application_id);

COMMIT;
